[package]
name = "lyrian"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lindera = "0.8.0"
lindera-core = "0.8.0"
serde = "1.0.130"
